#!/bin/sh

read -p "백업 필요 없죠? " fdzz

[ ! "$fdzz" = "ㄹㅇㅋㅋ" ] && exit 1

read -p "진짜 지워요???? " fdzz

[ ! "$fdzz" = "ㄹㅇㅋㅋ" ] && exit 1

read -p "지운다????????? " fdzz

[ ! "$fdzz" = "ㄹㅇㅋㅋ" ] && exit 1

if /bin/rm "$@"; then
    echo "지웠음!!!!!!!!!"
else
    echo "못 지웠음ㅠㅠㅠ"
fi
